### ISSUE TITLE
Showing icon in front of inline title

### ISSUE THREAD

**Issue by kbhbhk** [FlorianWoelki/obsidian-iconize#190]
### **Is your feature request related to a problem? Please describe.**

I just wish I could see the file's icon in the file content.

### **Describe the solution you'd like**

Add toggle option can show the file's icon in front of the inline title or above it like notion does.
It will makes the file easier to distinguish, I believe!

Maybe like this perhaps...:
<img width="621" alt="스크린샷 2023-06-03 오후 12 33 17" src="https://github.com/FlorianWoelki/obsidian-icon-folder/assets/130442702/3e8602dd-ea1e-405c-82e0-4e7e529ffb26">

Thanks!
I really like your plugin BTW 🙂

**Comment by Bluemoondragon07** [comment]
Yessss! @FlorianWoelki thank you sooooo much for adding this in the latest update! Thank you, thank you, thank you!🥳

**Comment by FlorianWoelki** [comment]
> Yessss! @FlorianWoelki thank you sooooo much for adding this in the latest update! Thank you, thank you, thank you!🥳

Sure thing! :) 

I forgot to close this issue. But this feature is available since the release of version 2.5.0.

**Comment by kbhbhk** [comment]
Really appreciate this! Thank you so much. 😊

**Comment by redactedscribe** [comment]
This is the first time I've added an icon since v2.7.1 was release with support for `icon:` and specifying emojis. My first impression was, why is the icon inline with the inline title? I personally think it would look nicer if it looked like this: `<emoji><space><title>`, rather than being placed above the title on its own line.
