### ISSUE TITLE
Icons cannot be found after setting up new device with Obsidian Sync

### ISSUE THREAD

**Issue by binaryDiv** [FlorianWoelki/obsidian-iconize#264]
**Describe the bug**
When setting up a new (mobile) device with Obsidian Sync and a predefined icon pack, icons that have been previously assigned to folders cannot be found (resulting in one popup error message per icon).

**To Reproduce**
1. Set up a vault with Obsidian Sync and install Iconize.
2. Download a predefined icon set (e.g. Lucide Icons).
3. Create folders and assign icons.
4. Set up the vault on a mobile device, enabling Obsidian Sync and plugin synchronization.
5. No icons are visible, instead you get popup error messages for every icon saying the icon was not found.

**Expected behavior**
Icons should be synchronized automatically when setting up a vault on a new device.

**Screenshots**
(Can be provided if needed.)

**Additional context**
I've encountered this bug yesterday with the current Iconize version on my personal vault. I will try to reproduce it with an empty test vault later, and then provide more detailed information.

I'd also like to debug the issue further (I think I've read in some thread that you (@FlorianWoelki) don't have Obsidian Sync and therefore cannot really test anything related to it?). However, I might need some help since I don't know exactly how the syncing mechanism works. Should the icons be unpacked from the icon pack **once** (as soon as they are used) and then synced using Obsidian Sync, or should every device unpack the needed icons on their own?

**Comment by eduardoagarcia** [comment]
I'm finding this same issue: icons/packs do not sync across devices. As I use obsidian in three places (work, personal, mobile) this is a challenge.

I found that if I use the git plugin to sync the actual settings, I can get things correct across my work and personal computers, but every time I open the obsidian app on my phone I get an entire screen full of "seems like you do not have the icon pack installed" error messages on open.

I'm about to uninstall the icon plugin :/

**Comment by FlorianWoelki** [comment]
At the moment, I am not able to do anything about this issue. There has been a discussion going on [in this thread](https://github.com/obsidianmd/obsidian-api/issues/134). For now, the only solution I can provide is to implement a background checker that adds the icons (see #242).

It might help to change the icon packs directory to `.obsidian/icons`.

**Comment by binaryDiv** [comment]
> It might help to change the icon packs directory to `.obsidian/icons`.

No, this does not help. (It was already set to this, since it's the default now.)

Reading the threads that you linked, I think there is a big misunderstanding about the `.obsidian/icons` directory. Putting anything there does explicitly **not** sync these files, so if you use that directory, you have to manually synchronize the icons in some way. And that's the intended behavior (as explained in the first paragraph of [this](https://github.com/obsidianmd/obsidian-api/issues/134#issuecomment-1731726522) comment).

Using the `.obsidian/icons` directory really only had one reason: Not clogging up the synchronization with lots of small files. If nothing gets synced, nothing can clog up. But also, well, nothing gets synced. So it really is not a solution, it's just disabling the feature completely.

I think with the new zip-file based approach, this "workaround" actually shouldn't be necessary anymore - at least as long as you don't overdo it with the icons. I've just tested it with a sandbox vault, using the `.obsidian/plugins/obsidian-icon-folder/icons` directory and the Lucide Icon pack. Every icon that I used was extracted from the zip file into that directory, and those were synced without any problems.

So to everyone with the same problem: Just set the icon directory to the old path of `.obsidian/plugins/obsidian-icon-folder/icons` - unless you're actively using hundreds/thousands of icons in your vault. (However, make sure that you start the synchronization only after 1. you've enabled syncing of the plugin settings and 2. you enabled community plugins - otherwise the syncing might get confused and delete your configs ... But this is an issue in Obsidian Sync itself, not this plugin.)

**Comment by FlorianWoelki** [comment]
> > It might help to change the icon packs directory to `.obsidian/icons`.
> 
> 
> 
> No, this does not help. (It was already set to this, since it's the default now.)
> 
> 
> 
> Reading the threads that you linked, I think there is a big misunderstanding about the `.obsidian/icons` directory. Putting anything there does explicitly **not** sync these files, so if you use that directory, you have to manually synchronize the icons in some way. And that's the intended behavior (as explained in the first paragraph of [this](https://github.com/obsidianmd/obsidian-api/issues/134#issuecomment-1731726522) comment).
> 
> 
> 
> Using the `.obsidian/icons` directory really only had one reason: Not clogging up the synchronization with lots of small files. If nothing gets synced, nothing can clog up. But also, well, nothing gets synced. So it really is not a solution, it's just disabling the feature completely.
> 
> 
> 
> I think with the new zip-file based approach, this "workaround" actually shouldn't be necessary anymore - at least as long as you don't overdo it with the icons. I've just tested it with a sandbox vault, using the `.obsidian/plugins/obsidian-icon-folder/icons` directory and the Lucide Icon pack. Every icon that I used was extracted from the zip file into that directory, and those were synced without any problems.
> 
> 
> 
> So to everyone with the same problem: Just set the icon directory to the old path of `.obsidian/plugins/obsidian-icon-folder/icons` - unless you're actively using hundreds/thousands of icons in your vault. (However, make sure that you start the synchronization only after 1. you've enabled syncing of the plugin settings and 2. you enabled community plugins - otherwise the syncing might get confused and delete your configs ... But this is an issue in Obsidian Sync itself, not this plugin.)
> 
> 
> 
> **EDIT:** However, I also think the background check that automatically unzips missing icons is a good idea. In combination with using the not-synced `.obsidian/icons` directory, this would allow to use lots of icons without performance issues with the syncing.

Now I finally get it thank you :D I'll describe that in the documentation. Thank you.

**Comment by FlorianWoelki** [comment]
I'll close this issue whenever the background checker was released. I'll also update the documentation about that.

So, having a few icons work but when having a lot of icons the recommended way would be to use the `.obsidian/icons` path with the background checker.

@binaryDiv could you roughly estimate how many Icons are necessary, so that Obsidian Sync is unusable?

**Comment by XVItokaz** [comment]
Hello,

I'm adding to this existing thread since the topic pertains to the same issue (Icons cannot be found after setting up a new device with Obsidian Sync).

Previously, I encountered a similar problem (https://github.com/FlorianWoelki/obsidian-iconize/issues/206), where FlorianWoelki, you had also provided assistance, for which I'm grateful. I was able to resolve it between my desktop PC and my MacBook Pro after some deep troubleshooting and fixes, including configuring the directory to .obsidian/icons.

However, after recently purchasing an iPad Pro and initially installing Obsidian with the old version of the icon folder, I couldn't make it work properly. Icons would only appear in some places but not all, exactly the same situation as my previous issue.

Subsequently, I noticed there had been an update to Iconize, so I updated the plugin. Unfortunately, this resulted in the disappearance of all icons. I can't see any icons now.

I'm unsure whether I should change the directory to .obsidian/plugins/obsidian-icon-folder/icons as suggested by binaryDiv, or if there's another way to resolve this.

What's particularly distressing is that when I performed this update on my iPad, it removed all icons from both my PC and Mac. I'm left with nothing now.

I suppose my question is, what configuration should I use to make it work? Should it be the same on all devices?

Thank you for your assistance.

**Comment by XVItokaz** [comment]
Thanks Florian

Then i wait for the fix before i continue setting new icons

**Comment by FlorianWoelki** [comment]
Please take a look at the [newest update](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.4.0). The background checker has been added.

I'll close this issue for now.

**Comment by Kribensisis** [comment]
Just finding this. It looks like the background checker actually doesn’t do anything to fix this issue. I have had this since the beginning with this plugin, and the introduction of the background checker only helped to synchronize the libraries between devices. It didn’t help with syncing the folder icons themselves. It still doesn’t.

Is this a technical limitation? Should there be something in the UI that tells users they will need to manually set folder icons on every one of their devices?

**Comment by Kribensisis** [comment]
Thanks @FlorianWoelki. I don’t follow your explanation in the second paragraph. It might be a translation issue.

I couldn’t get folder icons to sync consistently (even with the background check), so I moved on to another extension.

This could probably be closed again as a case that Iconize doesn’t support (consistent folder icon sync). It might be good to clearly label this in the UI since the issue has been around since the beginning and the extension is very popular 👍

**Comment by FlorianWoelki** [comment]
Maybe a quick question. Could you send a screenshot of which folders do not get synced?

**Comment by Kribensisis** [comment]
I don't have screenshots or would be glad to. I found that none of them synced til I switched to the default icons and regular emojis. But, even with those, if I changed one on my phone or tablet it didn't sync back to my Mac. Sorry I can't be more help!
