### ISSUE TITLE
Modify data.json to allow Syncthing to work with icons

### ISSUE THREAD

**Issue by Adham-A** [FlorianWoelki/obsidian-iconize#318]
**Is your feature request related to a problem? Please describe.**

I'm using syncthing to sync my obsidian vaults between my devices but one time out of 2 icons aren't saved properly and even disappear

**Describe the solution you'd like**

I tried to find the root of this issue and it happens that when Syncthing does it syncing it have issues handling data.json, as far as I'm aware since it saves a conflict file, when comparing both of them in vscode the issue is : 
- recentlyUsedIcons are different → Please allow setting the number to 0 for recently used actual minimum is 1
- The keys of notes : icons aren't in the same order, I'm not sure it would work but if maybe the notes were sorted it would help out this issue 

**Describe alternatives you've considered**

I have not found any so far beneath having to reselect my icons on all my devices

**Comment by FlorianWoelki** [comment]
I think it's due to the Obsidian sync mechanism. I've added some functionalities to prevent this issue. I'll close this issue for now. Feel free to create a new one, if needed.

If you have syncing issues, I recommend reading [this guide](https://florianwoelki.github.io/obsidian-iconize/guide/syncing.html#lucide-icons) which was also recently released.
