### ISSUE TITLE
Icons not available to choose

### ISSUE THREAD

**Issue by interconnectedMe** [FlorianWoelki/obsidian-iconize#393]
Hello, I hope the information below is helpful,

**Describe the bug**
During the last days, my icons disappeard from my notes in the Files view
Existing Folders, icons remain.
Existing and new notes, I see 'FasNoteSticky' pre-pended to each note name in Files view.

**To Reproduce**
Open obsidian
Look at Files view

**Expected behavior**
To see notes with icons instead of "FasNoteSticky.......Then_A_Filename"

**Screenshots**
![Screenshot 2024-03-12 121546](https://github.com/FlorianWoelki/obsidian-iconize/assets/155753650/1eec02e1-c600-47f2-8734-5d8ecdab3526)

**Additional context**
I am using Obsidian on Windows, and GNU/linux/KDE Neon

thanks for the awesome plugin!
DR

**Comment by FlorianWoelki** [comment]
This is potentially fixed in the newest release. I'll close this issue for now. Feel free to create a new one, if needed.

Additionally, if you have syncing issues, I recommend reading [this guide](https://florianwoelki.github.io/obsidian-iconize/guide/syncing.html#lucide-icons) which was also recently released.
