### ISSUE TITLE
Enable icon size larger than 24px

### ISSUE THREAD

**Issue by Valombreuse** [FlorianWoelki/obsidian-iconize#513]
Hi Florian,

First I want to thank you for your amazing plugin. You greatly improved it over the time. It is now a must have :)

I have a few requests :

- The max size of icons is 24 px. And it is rather small when you work on a 4k display. It would be cool if you could enable 32 or even 48 or 64 px (useful for those old guys like me that do not see very well)

- It also would be cool to provide a tutorial on custom icon rules as I discovered it is a great feature but there is a lack of info on it and the "plain string and regex format" is rather intimidating for non technical users like me. I happened to learn how to use it thanks to this issue post : https://github.com/FlorianWoelki/obsidian-iconize/issues/492. I guessed it more than it is intuitive though.

- It also would be cool to be able to select multiple notes or folders an assign them a icon with the right click menu.
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/128172024/a10e6bb2-50ec-44db-83e9-53f9e1af53ad)

- Also you cannot see in the full icon selection in the list (when you add or change an icon). There must be a limit number of displayed icons and that is really few. You cannot even see the full collection so searching "visually" is not easy.
- Also it would be cool to be able to exclude the emojis from the list.

Thanks
PogS

**Comment by FlorianWoelki** [comment]
Hey, thank you for all the great suggestions.

Let me answer bullet point by bullet point:
- Great suggestion. I've created a separate ticket for that #514 
- I agree, if you've got the time, could you create a tutorial in [the documentation (https://github.com/FlorianWoelki/obsidian-iconize/blob/main/docs/files-and-folders/custom-rules.md)?
- I think that's another feature, could you maybe create a separate issue for that?
- Seems for me related to #176 and #65 
- That also seems like another feature, could you also create another issue for that? 

All great suggestions, thanks! But, maybe you can create separate issues for the non-existing ones. Or create new issues and modify this one so that it highlights only one feature :D

**Comment by Valombreuse** [comment]
I  created 
- https://github.com/FlorianWoelki/obsidian-iconize/issues/515
- https://github.com/FlorianWoelki/obsidian-iconize/issues/516
